repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.8
  hooks:
    - id: ruff
      args: [ "check", "." ]
- repo: https://github.com/pytest-dev/pytest
  rev: 8.3.3
  hooks:
    - id: pytest
      additional_dependencies: []
      args: [ "-q", "-k", "unit or integration" ]
