"""Scan all HistData M1 pairs for bid/ask data-quality issues.

Walks every pair listed in ``configs/data_v3.yaml``, loads M1 via the
PR-A loader (warming the parquet cache as a side benefit), and tallies
``bid_ask_data_quality`` counts per pair. Writes a markdown report.

Usage::

    py scripts/data/histdata_quality_scan.py \\
        --config configs/data_v3.yaml \\
        --out docs/dispatches/pr_b_data_quality.md

The output is deterministic given the same M1 layer: same per-pair
counts, same totals, same row ordering (pairs sorted alphabetically).
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import yaml

from core.data.histdata_loader import load_m1
from core.spread.real_spread import collate_summaries, data_quality_summary


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", type=Path, default=Path("configs/data_v3.yaml"))
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("docs/dispatches/pr_b_data_quality.md"),
    )
    parser.add_argument(
        "--out-json",
        type=Path,
        default=None,
        help="Optional sidecar JSON with raw per-pair counts",
    )
    parser.add_argument(
        "--histdata-root",
        type=Path,
        default=None,
        help="Override data.histdata_root from config",
    )
    parser.add_argument(
        "--cache-root",
        type=Path,
        default=None,
        help="Override data.cache_root from config",
    )
    args = parser.parse_args()

    cfg = yaml.safe_load(args.config.read_text(encoding="utf-8"))
    pairs = sorted(cfg["pairs"])
    histdata_root = args.histdata_root or Path(cfg["data"]["histdata_root"])
    cache_root = args.cache_root or Path(cfg["data"]["cache_root"])

    summaries = []
    for pair in pairs:
        df = load_m1(pair, histdata_root=histdata_root, cache_root=cache_root)
        summ = data_quality_summary(df, pair=pair, tf="M1")
        summaries.append(summ)
        print(
            f"{pair:8s}  total={summ.total_bars:>10,}  ok={summ.ok:>10,}  "
            f"zero_or_neg={summ.zero_or_neg_spread:>6,}  "
            f"nan={summ.nan_bid_or_ask:>6,}  bad_pct={summ.bad_pct:.6%}"
        )

    totals = collate_summaries(summaries)
    print("\n----- TOTAL -----")
    print(json.dumps(totals, indent=2))

    # Write markdown report
    lines: list[str] = [
        "# PR-B Data Quality Scan — HistData M1 bid/ask",
        "",
        "Generated by `scripts/data/histdata_quality_scan.py` across all "
        "28 pairs listed in `configs/data_v3.yaml`. Counts ``bid_ask_data_quality`` "
        "buckets on each pair's full M1 history.",
        "",
        "## Per-pair breakdown",
        "",
        "| Pair | Total bars | OK | Zero/Neg spread | NaN bid/ask | Bad % |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for s in summaries:
        lines.append(
            f"| {s.pair} | {s.total_bars:,} | {s.ok:,} | "
            f"{s.zero_or_neg_spread:,} | {s.nan_bid_or_ask:,} | {s.bad_pct:.6%} |"
        )

    lines += [
        "",
        "## Totals",
        "",
        f"- **Pairs scanned:** {totals['n_summaries']}",
        f"- **Total M1 bars:** {totals['total_bars']:,}",
        f"- **OK bars:** {totals['ok']:,}",
        f"- **Zero or negative spread:** {totals['zero_or_neg_spread']:,}",
        f"- **NaN bid/ask:** {totals['nan_bid_or_ask']:,}",
        f"- **Bad total:** {totals['bad_total']:,} ({totals['bad_pct']:.6%} of all bars)",
        "",
        "## Treatment",
        "",
        "Per L_PROTOCOL §1 non-negotiable on real bid/ask, "
        "`bid_ask_data_quality != ok` bars are skipped by every trade-sim "
        "code path (`core.spread.real_spread.is_tradable_bar` is False on "
        "them). No fallback to any external spread-floor file.",
        "",
    ]

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"\nReport written to {args.out}")

    if args.out_json is not None:
        payload = {
            "per_pair": [s.as_dict() for s in summaries],
            "totals": totals,
        }
        args.out_json.parent.mkdir(parents=True, exist_ok=True)
        args.out_json.write_text(
            json.dumps(payload, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
            newline="\n",
        )
        print(f"Sidecar JSON written to {args.out_json}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
