pair: EURUSD
timeframe: D
from: 2020-01-01
to: 2021-12-31
roles:
  c1: c1_supertrend
  c2: null
  baseline: null
  volume: volume_rvol
  exit: null
params:
  c1:
    atr_period: 10
    multiplier: 3.0
  volume:
    lookback: 20
    k: 1.5
risk:
  use_spread: false
  commission_per_lot: 0.0
output_dir: parity/runs/volume_rvol_EURUSD_D1_2020_2021
