"""Bonferroni accounting + raw top-K ranking.

Per chat decision 3 (this conversation): the primary Bonferroni
denominator is ``N_evaluated`` (rules that passed BOTH the causal
filter AND the pool-size floor). The secondary report uses the full
search budget (10000) for transparency.

Per dispatch Override 1 + 5: ranking is by raw mean R; Bonferroni
significance is computed in addition, NOT used for ranking. Top-10 raw
performers go to ``top_10_raw.md``; Bonferroni survivors (rules whose
p-value clears ``0.05 / N_evaluated``) go to ``bonferroni_survivors.md``.

Per chat methodology constraint: top-3 spawn follow-up vanilla arcs;
ranks 4-10 are analysis-only. The ranking module marks this in its
output so the closure doc generator can distinguish the two cohorts.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence


@dataclass(frozen=True)
class BonferroniReport:
    """Bonferroni accounting at the population level."""

    n_generated: int                   # rules generated by random search (budget)
    n_evaluated: int                   # passed causal AND pool floor
    n_causal_rejected: int
    n_pool_floor_rejected: int
    alpha: float
    threshold_primary: float           # alpha / n_evaluated (or NaN if n=0)
    threshold_budget: float            # alpha / n_generated (transparency)

    @property
    def n_other_rejected(self) -> int:
        """Rules rejected for reasons other than causal / pool floor (e.g. degenerate)."""
        return max(
            0,
            self.n_generated
            - self.n_evaluated
            - self.n_causal_rejected
            - self.n_pool_floor_rejected,
        )


def build_bonferroni_report(
    n_generated: int,
    n_evaluated: int,
    n_causal_rejected: int,
    n_pool_floor_rejected: int,
    alpha: float = 0.05,
) -> BonferroniReport:
    if n_evaluated > 0:
        threshold_primary = alpha / n_evaluated
    else:
        threshold_primary = float("nan")
    if n_generated > 0:
        threshold_budget = alpha / n_generated
    else:
        threshold_budget = float("nan")
    return BonferroniReport(
        n_generated=int(n_generated),
        n_evaluated=int(n_evaluated),
        n_causal_rejected=int(n_causal_rejected),
        n_pool_floor_rejected=int(n_pool_floor_rejected),
        alpha=float(alpha),
        threshold_primary=threshold_primary,
        threshold_budget=threshold_budget,
    )


@dataclass(frozen=True)
class RankedRule:
    """One row in the top-K table."""

    rank: int
    rule_id: int
    pool_size: int
    mean_r: float
    p_value: float
    bonferroni_pass_primary: bool
    bonferroni_pass_budget: bool
    follow_up_eligible: bool   # True for ranks 1-3 only (chat methodology constraint)


def rank_top_k(
    rows: Sequence[dict],
    k: int,
    report: BonferroniReport,
    follow_up_top_k: int = 3,
) -> tuple[RankedRule, ...]:
    """Rank ``rows`` by mean R desc; return the top-k with Bonferroni flags.

    Each row dict must carry at least: ``rule_id``, ``pool_size``,
    ``mean_r``, ``p_value``. Rows with NaN mean R or pool_size==0 are
    excluded (they correspond to rejected rules).
    """
    eligible: list[dict] = [
        r for r in rows
        if r.get("pool_size", 0) > 0 and _is_finite(r.get("mean_r"))
    ]
    # Sort by mean_r desc, tie-broken by p_value asc, then rule_id asc.
    eligible.sort(key=lambda r: (-_safe_float(r["mean_r"]), _safe_float(r.get("p_value", 1.0)), int(r["rule_id"])))
    top = eligible[:k]
    out: list[RankedRule] = []
    for i, r in enumerate(top, start=1):
        p_val = _safe_float(r.get("p_value", float("nan")))
        pass_primary = (
            _is_finite(p_val)
            and _is_finite(report.threshold_primary)
            and p_val < report.threshold_primary
        )
        pass_budget = (
            _is_finite(p_val)
            and _is_finite(report.threshold_budget)
            and p_val < report.threshold_budget
        )
        out.append(
            RankedRule(
                rank=i,
                rule_id=int(r["rule_id"]),
                pool_size=int(r["pool_size"]),
                mean_r=float(r["mean_r"]),
                p_value=p_val,
                bonferroni_pass_primary=bool(pass_primary),
                bonferroni_pass_budget=bool(pass_budget),
                follow_up_eligible=(i <= follow_up_top_k),
            )
        )
    return tuple(out)


def bonferroni_survivors(
    rows: Sequence[dict],
    report: BonferroniReport,
) -> tuple[int, ...]:
    """Return the rule_ids that clear the PRIMARY Bonferroni threshold.

    Per chat decision 3: primary = alpha / N_evaluated. Budget threshold
    (alpha / 10000) is reported alongside but not used to select
    survivors.
    """
    if not _is_finite(report.threshold_primary):
        return tuple()
    survivors: list[int] = []
    for r in rows:
        p_val = _safe_float(r.get("p_value", float("nan")))
        if not _is_finite(p_val):
            continue
        if r.get("pool_size", 0) <= 0:
            continue
        if p_val < report.threshold_primary:
            survivors.append(int(r["rule_id"]))
    return tuple(sorted(survivors))


# ── helpers ────────────────────────────────────────────────────────────


def _safe_float(x) -> float:
    try:
        return float(x)
    except (TypeError, ValueError):
        return float("nan")


def _is_finite(x) -> bool:
    try:
        f = float(x)
    except (TypeError, ValueError):
        return False
    return f == f and f not in (float("inf"), float("-inf"))


__all__ = (
    "BonferroniReport",
    "build_bonferroni_report",
    "RankedRule",
    "rank_top_k",
    "bonferroni_survivors",
)
