# C1-only sweep configuration
role_filters: ["c1"]

discover:
  c1: true
  c2: false
  baseline: false
  volume: false
  exit: false

allowlist:
  c1: ["c1_supertrend", "c1_twiggs_money_flow", "c1_disparity_index", "c1_aroon", "c1_doda_stochastic", "c1_vortex_indicator", "c1_forecast", "c1_ttf", "c1_zerolag_macd"]
blocklist:
  c1: []

roles:
  c1: []   # auto-discover from allowlist

default_params:
  c1: {}

static_overrides:
  pairs: ["EUR_USD", "GBP_USD", "USD_JPY", "AUD_USD", "USD_CHF", "USD_CAD", "NZD_USD", "EUR_JPY", "GBP_JPY", "AUD_JPY", "EUR_GBP", "AUD_NZD"]
  timeframe: "D"
  date_range:
    start: "2015-01-01"
    end: "2024-12-31"
  output:
    results_dir: "results_history/c1_sweep"
  spreads:
    enabled: false
  filters:
    dbcvix:
      enabled: false
  rules:
    one_candle_rule: false
    pullback_rule: false
  tracking:
    track_win_loss_scratch: true
    track_roi: true
    track_drawdown: true

parallel:
  workers: auto
  max_runs: null

scoring:
  roi_pct_w: 1.0
  max_dd_w: 0.7
  trades_penalty_w: 0.0
  min_trades: 0
